"""
Django settings for D13 project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&0#i&2bsq6&+b*ua@o1grj&)h(t3ji_+2c$l5_c$izei0msc-$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'logging_d13',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'D13.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'D13.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

def debug_filter(message): 
    return (message.levelname == 'INFO') or (message.levelname == 'DEBUG')

def warning_filter(message): 
    return message.levelname == 'WARNINH'

def error_filter(message): 
    return (message.levelname == 'ERROR') or (message.levelname == "CRITICAL")

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'style' : '{', 
    'formatters': {
        'deb': {
            'format': '%(asctime)s %(levelname)s %(message)s',
            'datefmt': '%Y.%m.%d %H:%M:%S',
        },
        'war': {
            'format': '%(asctime)s %(levelname)s %(message)s %(pathname)s',
            'datefmt': '%Y.%m.%d %H:%M:%S',
        },
        'err': {
            'format': '%(asctime)s %(levelname)s %(message)s %(pathname)s %(exc_info)s',
            'datefmt': '%Y.%m.%d %H:%M:%S',
        },
        'general_log_format': {
            'format': '%(asctime)s %(module)s %(message)s',
            'datefmt': '%Y.%m.%d %H:%M:%S',
        },
        'security_log': {
            'format': '%(asctime)s %(levelname)s %(module)s %(message)s',
            'datefmt': '%Y.%m.%d %H:%M:%S',
        },
        'email': {
            'format': '%(asctime)s %(levelname)s %(message)s %(pathname)s',
            'datefmt': '%Y.%m.%d %H:%M:%S',
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'debug_filter': {
            '()': 'django.utils.log.CallbackFilter',
            'callback': debug_filter,
        },
        'warning_filter': {
            '()': 'django.utils.log.CallbackFilter',
            'callback': warning_filter,
        },
         'error_filter': {
            '()': 'django.utils.log.CallbackFilter',
            'callback': error_filter,
        },
    },
    'handlers': {
        'deb': {
            'level': 'DEBUG',
            'filters': ['debug_filter', 'require_debug_true',],
            'class': 'logging.StreamHandler',
            'formatter': 'deb'
        },
        'war': {
            'level': 'WARNING',
            'filters': ['warning_filter', 'require_debug_true',],
            'class': 'logging.StreamHandler',
            'formatter': 'war'
        },
        'err': {
            'level': 'ERROR',
            'filters': ['error_filter', 'require_debug_true',],
            'class': 'logging.StreamHandler',
            'formatter': 'err'
        },
        'general_log': {
            'level': 'INFO',
            'formatter': 'general_log_format',
            'filters': ['require_debug_false',],
            'class': 'logging.FileHandler',            
            'filename': 'log/general.log',
        },
        'errors_log': {
            'level': 'ERROR',
            'formatter': 'err',
            'class': 'logging.FileHandler',            
            'filename': 'log/errors.log',
        },
        'security_log': {
            'level': 'DEBUG',
            'formatter': 'security_log',
            'class': 'logging.FileHandler',            
            'filename': 'log/security.log',
        },
        'mail_admins': {
            'level': 'ERROR',
            'formatter': 'email',
            'class': 'django.utils.log.AdminEmailHandler',
            'email_backend': 'django.core.mail.backends.filebased.EmailBackend',
        }
    },
    'loggers': {
        'django': {
            'level': 'INFO',
            'handlers': ['deb', 'war', 'err', 'general_log'],
            'propagate': True,
        },
        'django.request': {
            'handlers': ['mail_admins', 'errors_log'],
            'level': 'ERROR',
            'propagate': True,
            'email_backend': 'django.core.mail.backends.filebased.EmailBackend',
        },
        'django.server': {
            'handlers': ['errors_log', 'mail_admins'],
            'level': 'ERROR',
            'propagate': True,
        },
        'django.template': {
            'handlers': ['errors_log'],
            'level': 'ERROR',
            'propagate': True,
        },
        'django.db.backends': {
            'handlers': ['errors_log'],
            'level': 'ERROR',
            'propagate': True,
        },
        'django.security': {
            'handlers': ['security_log'],
            'level': 'DEBUG',
            'propagate': True,
        },
    }
}
